Added CLI
policumbent/bob pull request #32
Opened 2022-05-24 17:08 UTC by davideaimar

2022-06-04 17:00 UTC, gabelluardo requested changes

2022-06-05 08:17 UTC, davideaimar commented on bobcli/bobcli/main.py
> +    with open(bob_root / 'utility/example_module/src/main.py') as f:
In ogni caso il modulo creato sarebbe solo una base, per cui un main standard secondo me ci può stare, poi si modifica come lo si vuole.

2022-06-05 15:10 UTC, gabelluardo commented on bobcli/bobcli/main.py
> +    with open(bob_root / 'utility/example_module/src/main.py') as f:
yep, solo con questo è abbastanza generico

```python
import asyncio


async def main():
    pass


def entry_point():
    asyncio.run(main())


if __name__ == "__main__":
    entry_point()

```

quando abbiamo le api di mqtt possiamo aggiornarlo e aggiungere un boilerplate anche di quello

2022-06-14 10:26 UTC, gabelluardo approved these changes

2022-06-14 13:49 UTC, merged